### PR TITLE
Add melpazoid github action

### LINKED ISSUE #16: Include useful github actions
bqn-mode is a somewhat simple package, in the sense it is just a set of files to be read by Emacs. In this sense it works very well. 

However, in order to include it in MELPA database, there are many rules to follow. We need some way to automatize this.

### PR DESCRIPTION
**Pull request by svmhdvn**
Fixes #16
Makes progress on #1 

Seems to work well https://github.com/svmhdvn/bqn-mode/actions/runs/4165077860/jobs/7207579595

### CODE REVIEW

**Comment by AndersonTorres** [comment]
It looks like a good time to fix many issues!

Or the link you provide is not running on the most recent trunk? 

EDIT: it is. Now I am interested in silencing the warnings before including melpazoid!

**Comment by AndersonTorres** [comment]
<details>
  <summary>Melpazoid output</summary>

Run echo $GITHUB_REF && make -C ~/melpazoid
refs/heads/trunk
make: Entering directory '/home/runner/melpazoid'
python3 melpazoid/melpazoid.py
Using local repository at /home/runner/work/bqn-mode/bqn-mode

make[1]: Entering directory '/home/runner/melpazoid'
sha256:a9e90aa10462bf8e9ea0752801fed4c269aa056b6d14f6a4e6b7971fa29084fb

`bqn-comint.el` with package-lint 20221003.1636:
```
3 issues found:
1:42: warning: You should depend on (emacs "24.1") if you need lexical-binding.
74:5: error: You should depend on (emacs "24.1") if you need `pop-to-buffer-same-window'.
138:3: error: You should depend on (emacs "24.3") if you need `setq-local'.
```

`bqn-comint.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- bqn-comint.el#L80: It's safer to sharp-quote function names; use `#'`
- bqn-comint.el#L146: It's safer to sharp-quote function names; use `#'`
- bqn-comint.el#L146: Loading a package should rarely add hooks
```

`bqn-glyph-mode.el` with package-lint 20221003.1636:
```
1 issue found:
79:3: error: You should depend on (emacs "24.3") if you need `read-only-mode'.
```

`bqn-help.el` with package-lint 20221003.1636:
```
8 issues found:
1:42: warning: You should depend on (emacs "24.1") if you need lexical-binding.
65:3: error: You should depend on (emacs "24.3") if you need `setq-local'.
66:3: error: You should depend on (emacs "24.3") if you need `setq-local'.
74:3: error: You should depend on (emacs "25.1") or the seq package if you need `seq-filter'.
80:5: error: You should depend on (emacs "26.1") if you need `if-let*'.
90:5: error: You should depend on (emacs "26.1") if you need `if-let*'.
97:11: error: You should depend on (emacs "24.3") if you need `read-only-mode'.
102:11: error: You should depend on (emacs "24.3") if you need `read-only-mode'.
```

`bqn-help.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- bqn-help.el#L83: No `format` required; `message` takes an f-string
- bqn-help.el#L84: No `format` required; `message` takes an f-string
- bqn-help.el#L105: No `format` required; `message` takes an f-string
- bqn-help.el#L99: `concat` may be unneeded; `insert` can take multiple arguments
```

`bqn-key-prefix.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- bqn-key-prefix.el#L1: `lexical-binding` must be on the end of the first line
```

`bqn-keymap-mode.el` with package-lint 20221003.1636:
```
1 issue found:
67:3: error: You should depend on (emacs "24.3") if you need `read-only-mode'.
```

`bqn-mode-map.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- bqn-mode-map.el#L25: There is no need to quote lambdas (neither #' nor ')
- bqn-mode-map.el#L1: `lexical-binding` must be on the end of the first line
```

`bqn-mode.el` with package-lint 20221003.1636:
```
4 issues found:
1:43: warning: You should depend on (emacs "24.1") if you need lexical-binding.
44:3: error: You should depend on (emacs "24.3") if you need `setq-local'.
45:3: error: You should depend on (emacs "24.3") if you need `setq-local'.
46:3: error: You should depend on (emacs "24.3") if you need `setq-local'.
```

`bqn-symbols-doc.el` with package-lint 20221003.1636:
```
4 issues found:
1:67: warning: You should depend on (emacs "24.1") if you need lexical-binding.
22:10: error: You should depend on (emacs "24.4") if you need `subr-x'.
3206:3: error: You should depend on (emacs "24.4") if you need `hash-table-keys'.
3211:3: error: You should depend on (emacs "25.1") if you need `when-let'.
```

`bqn-symbols.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- bqn-symbols.el#L1: `lexical-binding` must be on the end of the first line
```

`bqn-syntax.el` with [melpazoid](https://github.com/riscy/melpazoid):
```
- bqn-syntax.el#L12: Triple semicolons `;;;` are usually for section headings
- bqn-syntax.el#L13: `lexical-binding` must be on the end of the first line
```

Package and license:
- Other (via API)
  - Try to use a standard license file format
    See: https://github.com/licensee/licensee
- GNU General Public License v3.0 or later -- bqn-comint.el: BQN comint mode
- GNU General Public License v3.0 or later -- bqn-glyph-mode.el: BQN glyph reference
- GNU General Public License v3.0 or later -- bqn-help.el: Help for BQN mode
- GNU General Public License v3.0 or later -- bqn-key-prefix.el: BQN input key prefix bindings
- GNU General Public License v3.0 or later -- bqn-keymap-mode.el: BQN Keymap Reference
- GNU General Public License v3.0 or later -- bqn-mode-map.el: BQN mode keymap input helpers
- bqn-mode-pkg.el -- consider excluding; MELPA creates one
- GNU General Public License v3.0 or later -- bqn-mode.el: Emacs mode for BQN
- GNU General Public License v3.0 or later -- bqn-symbols-doc.el: Documentation table for BQN symbols
- GNU General Public License v3.0 or later -- bqn-symbols.el: BQN symbols
- GNU General Public License v3.0 or later -- bqn-syntax.el: BQN font lock definitions

make: *** [Makefile:6: run] Error 2
make: Leaving directory '/home/runner/melpazoid'
Error: Process completed with exit code 2.

</details>

**Comment by AndersonTorres** [comment]
I am not understanding the errors of package-lint. It is complaining about emacs 24.3, however it is precisely the required version at package-requires comment line.

**Comment by svmhdvn** [comment]
Give me a bit of time to correctly fix these in my fork's branch, please don't add commits to it while I'm iterating on it. I think I should have them all fixed soon.

**Comment by svmhdvn** [comment]
@AndersonTorres ready for review now.

**Pull request merged**
