### PR TITLE
Help cleanup

### PR DESCRIPTION
**Pull request by ilohmar**
These are various changes to clean up eldoc and documentation facilities.

By far the most offensive change is the first commit, removing a user command --- the commit message explains the rationale.

### CODE REVIEW

**Comment by ilohmar** [comment]
The failing checks seem to be a melpazoid/python issue.  The checkdoc "warnings" mostly already existed before these commits and are, IMHO, largely non-sensical or even wrong.

**Comment by AndersonTorres** [comment]
The checkdoc issues are harmless, maybe emacs is being too strict.

**Comment by AndersonTorres** [comment]
Given that it inserts a breaking change (albeit minor and not too harmful), I will tag-release it.

**Comment by ilohmar** [comment]
Great.  I do have a number of simplifications I will turn into PR(s) today, but my final goal (merging the symbols documentation and the symbols/key table) will probably only happen at some point over this weekend.  These changes will be mostly internal, anyway.

**Pull request merged**
